import Footer from '@/components/Footer';
import NavBar from '@/components/NavBar';
import '@/styles/globals.css';
import { Montserrat } from 'next/font/google';
import Head from 'next/head';
import { ThemeProvider } from 'next-themes';
import ToggleButton from '@/components/ToggleButton';

const montserrat = Montserrat({
  subsets: ['latin'],
});
 
export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Vincent Hsieh</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider attribute="class">
        <main className={`${montserrat.className} font-mont dark:bg-dark`}>
          <NavBar />
          <Component {...pageProps} />
          <Footer />
        </main>
      </ThemeProvider>
    </>
  );
}
